name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install docsify-cli
        run: npm i -g docsify-cli

      - name: Create images directory
        run: mkdir -p images

      - name: Copy logo to images directory
        run: |
          if [ -f .gitbook/assets/exchequer_logo.png ]; then
            cp .gitbook/assets/exchequer_logo.png images/
          else
            # Create a placeholder if the logo doesn't exist
            echo "Logo not found, creating placeholder"
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
