name: Deploy HonKit to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main # Or 'master', or whatever your default branch is named

  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Permissions needed by the job
    permissions:
      contents: write # Allow the job to write to the repository (to push to gh-pages)

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up Node.js in the runner environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Using Node.js version 20 (current LTS as of May 2025). You can use '18' or other LTS versions.
          cache: 'npm' # Caches npm dependencies to speed up future builds

      # Step 3: Installs your project dependencies (including HonKit)
      - name: Install dependencies
        run: npm ci # 'npm ci' is generally recommended for CI environments for faster, more reliable installs than 'npm install'

      # Step 4: Builds your HonKit site
      # This assumes you have a script "docs:build": "honkit build" in your package.json
      - name: Build HonKit site
        run: npm run docs:build

      # Step 5: Deploys the built site (from the _book directory) to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book # The directory HonKit builds to
          # publish_branch: gh-pages # This is the default, branch will be created if it doesn't exist
          # user_name: 'github-actions[bot]' # Optional: Name of the committer
          # user_email: 'github-actions[bot]@users.noreply.github.com' # Optional: Email of the committer
          # cname: your.customdomain.com # Optional: if you use a custom domain, uncomment and set this
          # allow_empty_commit: false # Default is false; set to true if you want to push even if no changes
